# jobs 用于执行不同的build stage
jobs:
  include:
    - stage: test
      os: linux
      language: generic
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # Flutter依赖
            - libstdc++6
            - fonts-droid
      before_script:
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
      script:
        - "./flutter/bin/flutter upgrade"
        - "./flutter/bin/flutter test"
    - stage: deployAPK
      os: linux
      language: android
      licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      # 以上都是在安装AndroidSDK
      env: APK_OUTPUT=build/app/outputs/apk/release/app-release.apk
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      #以上为Flutter环境搭建
      before_script:
        # 用你自己的解密命令替代
        - openssl aes-256-cbc -K $encrypted_074b4fbb9b77_key -iv $encrypted_074b4fbb9b77_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar -C android/
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1

        #蒲公英上传脚本
        - cd $TRAVIS_BUILD_DIR
        - wget -c https://raw.githubusercontent.com/Pgyer/TravisFile/master/pgyer_upload.sh -O pgyer_upload.sh
        - chmod +x pgyer_upload.sh
      script:
        - "./flutter/bin/flutter upgrade"
        - "./flutter/bin/flutter -v build apk --release"
      deploy:
        provider: releases
        skip_cleanup: true
        # 用你的api_key替代
        api_key:
          secure: qACR41yhrLxnq/MNsQPxv1DIWDI319EE68sE204mhNfEvqCt6TOfbEnLQ/0TYYdGatzh6G2N3YoJzkTmKPXC37qBUUCpYbbzDC/RSIX/a9xKtBsNep3PzzymHQ15jB16iLgFcPrBKyuqzkJAk1ev3Az9OzUsWFj4JSwLyvznpjlz+Iv5ai17PfjFTdcj6393whEs47e7F3ZNiDpam6fB8PMpAHKu2kN3IBt+XQW/dumKMHxDN3NtLo/KH0uIg0LT0cJvYU72qtQuCya5QfyTzh4VWp9jS0Twesx27KtL/2kf3MC0M3dl5SlPzxa7Ia9fTru6tMhneLG8LwqatmyqX5WDPKwk9d0bkdAoaumOwZL8fVmu8E34KXWgt2UOVU2NOtpeuEhD6hymANCVn4JrUXzL/hMsVFjrDhhazk6P+jq0v3sWnPx1H1Brng8SyQcBE3p3jZfakn2rlMshpyB5DIc0HKbcme+zdsQer7NU/Djft6rQ5kdZqHp/4yuaz2ih/U25lmd5rcJr+PDJzPTMEi0qbV0rNRij1LQcMS7CAk8y6h34WsZJO7seYLbBvbaBvJjBZ2QsuT5ugMbVkk3ZIvN7A6GpT6LXpvghdcSGtE9Mvjxe55Nx4UciAGrhrS8ffYO/jcvV4/yxoXByo/6cLK8heu45lDnmWa0aGD2O/sc=
        file: $APK_OUTPUT
        on:
          tags: true

      # 在apk上传到GitHub后，使用蒲公英的上传脚本将apk上传到蒲公英
      after_deploy:
        - set -e
        - $TRAVIS_BUILD_DIR/pgyer_upload.sh "${TRAVIS_BUILD_DIR}/app/build/outputs/apk/release/app-release.apk" $PGYER_API_KEY

# TODO
#    - stage: deployIPA
#      os: osx
#      language: objective-c
#      osx_image: xcode9.2
#      before_script:
#        - pip2 install six
#        - brew update
#        - brew install libimobiledevice
#        - brew install ideviceinstaller
#        - brew install ios-deploy
#        # 以上安装xcode环境
#        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
#      script:
#        - "./flutter/bin/flutter upgrade"
#        - gem install cocoapods
#        - pod setup
#        - "./flutter/bin/flutter -v build ios --release --no-codesign"
#        - mkdir Runner
#        - mkdir Runner/Payload
#        - cp -r build/ios/iphoneos/Runner.app Runner/Payload/Runner.app
#        - cd Runner
#        - zip -r Runner.ipa Payload
#      deploy:
#        provider: releases
#        skip_cleanup: true
#        #跟Android的api_key是一致的
#        api_key:
#          secure: G+7dKkugZcG3VjZkIQ6CMemwHwcPkpBiJikW7jonxKOrhIFpCeKk2MkY+tCJU4hd48z2prS78U+7yCnzU6R9qMqlQ75giIlTrNaPoHzhKoeafutrOkUjd80FgCQwoqaYADEO+2IntmLQ2t9W/1T1rI5IeTvRfoM2b+C9A+vmRW9t8KYmYBRSGzXKbMQhW4d4nZKWTaJliyu5Q2mT6eWAnMVUyyQiKoods+La77ZsUB5wOVIwnhhDzUjbjtcy7MsjdtQ5jXyNOOlLfPBYQVg8aQfp5459m81ejnQsMxBhhfNehbEtOP7zvq8PwS0RF3lYb27s2LJA3jVlADXYWUJHTyScurOyxSgOsqi8sJG/U/lj/ZAx49d0/G+jq7NFiIxsCDnfwuGfiGxE1NjUr5RUk5ifo3xhJVagLuoJVEcMhvCmwvdb9x9NzMyGXe9BTcDvylKWGYFvygFGTOHIyl954CPBm0fgBHgpfODGR0LOMsFu/Iggqc/Pw71FVZ0Oc+6r1JI/dxsdW2Eh/gpBTNijjZbk9VghymWTBpwpQm6Dkjv6au6w+VjAkdmHQ8IyicBsIfEJW1qgGT5t+sn/TuQ6SP9WRb0uB09P5oXeOWBpQjXzdrlrcCt5ylweTorEu3QCfawBZZHNvBLIDQxKQOY2ufxxSiNdmBDqtDi5HgfdljI=
#        file: Runner.ipa
#        on:
#          tags: true
